export const products = [
  {
    coverImage: './assets/img/phone-cover.jpg',
    id: 1,
    name: 'Phone XL',
    price: 799,
    description: 'A large phone with one of the best screens',
    heading1: 'Phone XL heading1',
    heading2: 'Phone XL heading2',
    heading3: 'Phone XL heading3',
  },
  {
    coverImage: './assets/img/phone-cover.jpg',
    id: 2,
    name: 'Phone Mini',
    price: 699,
    description: 'A great phone with one of the best cameras',
    heading1: 'Phone Mini heading1',
    heading2: 'Phone Mini heading2',
    heading3: 'Phone Mini heading3',
  },
  {
    coverImage: './assets/img/phone-cover.jpg',
    id: 3,
    name: 'Phone Standard',
    price: 299,
    description: '',
    heading1: 'Phone Standard heading1',
    heading2: 'Phone Standard heading2',
    heading3: 'Phone Standard heading3',
  },
  {
    coverImage: './assets/img/phone-cover.jpg',
    id: 4,
    name: 'Phone Special',
    price: 900,
    description: '',
    heading1: 'Phone Special heading1',
    heading2: 'Phone Special heading2',
    heading3: 'Phone Special heading3',
  },
];
